version: "3"

volumes:
  pgdata:
  data-dashboard:

services:
  postgres:
    image: "openmaptiles/postgis:2.9"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432
    env_file: .env

  tiles:
    image: osmwithoutborders/cosmogony-tiles
    env_file: .env
    depends_on:
      - postgres
    ports:
      - 6767

  api:
    image: osmwithoutborders/cosmogony-api
    env_file: .env
    depends_on:
      - postgres
    ports:
      - 8000

  explorer:
    image: osmwithoutborders/cosmogony-explorer
    depends_on:
      - api
    ports:
      - 8585:80  # TODO remove this
    volumes:
      - data-dashboard:/mnt/data_dashboard
